---
- hosts: masters
  tasks:
    - name: Get join command
      shell: kubeadm token create --print-join-command
      register: join_command_raw
    - name: Set join command
      set_fact:
        join_command: "{{ join_command_raw.stdout_lines[0] }}"

- hosts: workers
  become: yes
  tasks:
    - name: Magic | play_hosts
      debug: var=hostvars['master1'].join_command
    - name: Reset master node
      shell: kubeadm reset -f
    - name: Disable swap
      command: swapoff -a
    - name: Join cluster
      shell: "{{ hostvars['master1'].join_command }}"
